[package]
name = "diesel-dtrace"
version = "0.1.0"
edition = "2021"
authors = ["Benjamin Naecker <ben@oxide.computer>"]
license = "Apache-2.0"
repository = "https://github.com/oxidecomputer/diesel-dtrace.git"

[dependencies]
diesel = { git = "https://github.com/diesel-rs/diesel", rev = "ce77c382", features = [ "r2d2" ] }
usdt = "0.2"

[dev-dependencies]
diesel = { git = "https://github.com/diesel-rs/diesel", rev = "ce77c382", features = [ "postgres", "r2d2" ] }
tokio = { version = "1", features = [ "macros", "rt-multi-thread" ] }
async-bb8-diesel = { git = "https://github.com/oxidecomputer/async-bb8-diesel", rev = "22c26ef" }
bb8 = "0.7"
