[package]
name = "diesel-dtrace"
version = "0.1.0"
edition = "2021"
authors = ["Benjamin Naecker <ben@oxide.computer>"]
license = "Apache-2.0"
repository = "https://github.com/oxidecomputer/diesel-dtrace.git"

[dependencies]
diesel = { version = "2.0.0-rc.0", features = [ "r2d2", "i-implement-a-third-party-backend-and-opt-into-breaking-changes" ] }
serde = "1"
usdt = "0.3"
uuid = { version = "0.8", features = [ "v4", "serde" ] }

[dev-dependencies]
diesel = { version = "2.0.0-rc.0", features = [ "postgres", "r2d2", "i-implement-a-third-party-backend-and-opt-into-breaking-changes" ] }
tokio = { version = "1", features = [ "macros", "rt-multi-thread" ] }
async-bb8-diesel = { git = "https://github.com/oxidecomputer/async-bb8-diesel", branch = "diesel2" }
bb8 = "0.8"
