#
# Configuration for GitHub-based CI, based on the stock GitHub Rust config.
#
name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-style:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Report cargo version
      run: cargo --version
    - name: Report rustfmt version
      run: cargo fmt -- --version
    - name: Check style
      run: cargo fmt -- --check

  stable-test:
    name: Verify stable toolchain
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    steps:
    - name: install-pq-mac
      if: ${{ matrix.os == 'macos-latest' }}
      run: brew install libpq
    - uses: actions/checkout@v6
    - uses: dtolnay/rust-toolchain@stable
    - name: Build
      env:
        PQ_LIB_DIR: /opt/homebrew/opt/libpq/lib
      run: cargo build --tests --verbose
    - name: Run tests
      env:
        PQ_LIB_DIR: /opt/homebrew/opt/libpq/lib
      run: cargo test --verbose

  nightly-test:
    name: Verify nightly toolchain
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    steps:
    - name: install-pq-mac
      if: ${{ matrix.os == 'macos-latest' }}
      run: brew install libpq
    - uses: actions/checkout@v6
    - uses: dtolnay/rust-toolchain@nightly
    - name: Build
      env:
        PQ_LIB_DIR: /opt/homebrew/opt/libpq/lib
      run: cargo build --tests --verbose
    - name: Run tests
      env:
        PQ_LIB_DIR: /opt/homebrew/opt/libpq/lib
      run: cargo test --verbose
