#
# Configuration for GitHub-based CI, based on the stock GitHub Rust config.
#
name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-style:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Report cargo version
      run: cargo --version
    - name: Report rustfmt version
      run: cargo fmt -- --version
    - name: Check style
      run: cargo fmt -- --check

  stable-test:
    name: Verify stable toolchain
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    steps:
    - name: install-pq-mac
      if: ${{ matrix.os == 'macos-latest' }}
      env:
        PQ_LIB_DIR: "$(brew --prefix libpq)/lib"
        LIBRARY_PATH: "/opt/homebrew/lib:$LIBRARY_PATH"
        PKG_CONFIG_PATH: "/opt/homebrew/lib/pkgconfig:$PKG_CONFIG_PATH"
        PATH: "/opt/homebrew/bin:$PATH"
      run: brew install postgresql
    - uses: actions/checkout@v5
    - uses: dtolnay/rust-toolchain@stable
    - name: Build
      run: cargo build --tests --verbose
    - name: Run tests
      run: cargo test --verbose

  nightly-test:
    name: Verify nightly toolchain
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    steps:
    - name: install-pq-mac
      if: ${{ matrix.os == 'macos-latest' }}
      env:
        PQ_LIB_DIR: "$(brew --prefix libpq)/lib"
        LIBRARY_PATH: "/opt/homebrew/lib:$LIBRARY_PATH"
        PKG_CONFIG_PATH: "/opt/homebrew/lib/pkgconfig:$PKG_CONFIG_PATH"
        PATH: "/opt/homebrew/bin:$PATH"
      run: brew install postgresql
    - uses: actions/checkout@v5
    - uses: dtolnay/rust-toolchain@nightly
    - name: Build
      run: cargo build --tests --verbose
    - name: Run tests
      run: cargo test --verbose
